## 3. Machine Learning with Python.
##     Linear Regression Multiple Variables

**Problem Statement.**

*In this machine learning tutorial we are going to predict the salaries of candidates.
there is hiring.csv file. this file contain hiring statics for a firm such as experience of candidate,his written test score
and personal interview score.Based on these 3 factors,HR will decide the salary.given this data,you need to build a machine learning model for HR department that can help them decide salaries for future candidates.Using this predict salaries for following candidates.*

**2 Yr Experience,9 test score,6 interview score**

**12 Yr Experience,10 test score,10 interview score**

In [1]:
import pandas as pd 
import numpy as np
from sklearn import linear_model

In [17]:
df=pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [18]:
df.experience =df.experience.fillna(0)

In [19]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [22]:
df.drop("salary($)",axis=1)

experience  test_score(out of 10)  interview_score(out of 10)
0         0.0                    8.0                           9
1         0.0                    8.0                           6
2         5.0                    6.0                           7
3         2.0                   10.0                          10
4         7.0                    9.0                           6
5         3.0                    7.0                          10
6        10.0                    NaN                           7
7        11.0                    7.0                           8

In [23]:
import math

In [25]:
median_test_score= math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [26]:
df['test_score(out of 10)']= df['test_score(out of 10)'].fillna(median_test_score)

In [27]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [32]:
reg= linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [33]:
reg.predict([[2,9,6]])

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [34]:
reg.predict([[12,10,10]])

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [36]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [40]:
reg.intercept_

14992.651446693126

In [44]:
# y = m1*x1+m2*x2+m3*x3+b
 # here we calculate the salary of 12yr experience candidate
2922.26901502*12+2221.30909959*10+2147.48256637*10+14992.651446693126 

93747.79628653314